export const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
export const MONTH_LOOKUP = Object.fromEntries(MONTHS.map((m,i)=>[m.toLowerCase(),i+1]));

export const DEFAULT_TRACKERS = [
  {id:'apartment-collisions',name:'Walked into an object (Apartment)',kind:'event',status:'retired',aliases:['walked into an object','walked into something in my apartment','apartment collision']},
  {id:'mors-mutual',name:'Mors Mutual Calls',kind:'event',status:'intermittent',aliases:['mors mutual','moors mutual']},
  {id:'migraines',name:'Migraines',kind:'event',status:'intermittent',aliases:['migraine','migraines']},
  {id:'hong-kong',name:'Hong Kong Spawns',kind:'event',status:'intermittent',aliases:['hong kong spawn','spawned in hong kong','hong kong']},
  {id:'google-car',name:'GTA Google Car Casualties',kind:'event',status:'intermittent',aliases:['google car casualty','google car casualties','gta google car']},
  {id:'collision-count',name:'Collision Count',kind:'event',status:'intermittent',aliases:['collision count','collision']},
  {id:'geoguessr-10k',name:'Geoguessr 10K Streak',kind:'record',status:'active',aliases:['geoguessr 10k streak','10k streak','geoguessr streak']},
  {id:'daily-challenge',name:'Daily Challenge',kind:'streak',status:'active',aliases:['daily challenge','dc streak','daily challenge streak']},
  {id:'monty-dc',name:'Daily Challenge vs Monty',kind:'versus',status:'active',aliases:['daily challenge vs monty','dc vs monty','monty daily challenge']},
];

export function freshState(){const now=new Date().toISOString();return {version:1,createdAt:now,updatedAt:now,entries:{},monthlyReviews:{},yearlyReviews:{},occurrences:[],trackerOverrides:{},musicCache:{},rawImports:[],settings:{autoCloudSync:false,theme:'dark'}}}
export function isoToday(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`}
export function dateLabel(date,{weekday=true}={}){const d=new Date(`${date}T12:00:00`);return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',...(weekday?{weekday:'long'}:{})}).format(d)}
export function monthLabel(monthKey){const [y,m]=monthKey.split('-').map(Number);return `${MONTHS[m-1]} ${y}`}
export function monthKeyOf(date){return date.slice(0,7)}
export function yearOf(date){return Number(date.slice(0,4))}
export function daysInMonth(monthKey){const [y,m]=monthKey.split('-').map(Number);return new Date(y,m,0).getDate()}
export function shiftDay(date,amount){const [y,m,d]=date.split('-').map(Number);const x=new Date(Date.UTC(y,m-1,d+amount));return x.toISOString().slice(0,10)}
export function monthBounds(monthKey){const [y,m]=monthKey.split('-').map(Number);return {start:`${y}-${String(m).padStart(2,'0')}-01`,end:`${y}-${String(m).padStart(2,'0')}-${String(daysInMonth(monthKey)).padStart(2,'0')}`}}
export function splitEvents(text){return String(text||'').split(/\s*,\s*|\n+/).map(s=>s.trim()).filter(Boolean)}
function wordsToCount(s){const lower=s.toLowerCase();const direct=lower.match(/\b(\d{1,3})\s*(?:times|x|calls?|spawns?|casualties|collisions?)\b/);if(direct)return Math.max(1,Number(direct[1]));if(/\btwice\b/.test(lower))return 2;if(/\bthree times\b/.test(lower))return 3;if(/\bfour times\b/.test(lower))return 4;return 1}
function negatedMigraine(s){return /(almost\s+(?:got|had).*migraine.*(?:didn'?t|did not)|before (?:it|the headache) became a migraine|didn'?t (?:get|have) a migraine|not a migraine|avoided (?:a )?migraine|rid of .* before .*migraine)/i.test(s)}
function trackerDetection(trackerId,date,count,snippet,extra={}){return {id:`${trackerId}:${date}:${Math.random().toString(36).slice(2,9)}`,trackerId,date,count,source:'detected',snippet,...extra}}
export function detectFromEntry(date,text){
  const events=splitEvents(text);const out=[];
  const wholeMigraineNegated=/(?:started|start(?:ed)?|almost).*?migraine[\s\S]{0,500}?(?:before .*?became a migraine|rid of .*?before .*?migraine|didn'?t .*?migraine|did not .*?migraine)/i.test(String(text||''));
  let sawDailyComplete=false;let sawDailyMiss=false;
  for(const segment of events){const s=segment.toLowerCase();
    if(/\b(?:mors|moors) mutual\b/i.test(segment)) out.push(trackerDetection('mors-mutual',date,wordsToCount(segment),segment));
    if(/\bmigraine\b/i.test(segment)&&!wholeMigraineNegated&&!negatedMigraine(segment)) out.push(trackerDetection('migraines',date,wordsToCount(segment),segment));
    if(/hong kong/i.test(segment)&&/(spawn|spawned|spawned in)/i.test(segment)) out.push(trackerDetection('hong-kong',date,wordsToCount(segment),segment));
    if(/google car/i.test(segment)&&/(casualt|hit|killed|collision|ran into|destroy)/i.test(segment)) out.push(trackerDetection('google-car',date,wordsToCount(segment),segment));
    if(/walked into/i.test(segment)&&/(object|wall|door|counter|something)/i.test(segment)) out.push(trackerDetection('apartment-collisions',date,wordsToCount(segment),segment));
    const streak=segment.match(/(?:geoguessr|10k).*?streak\s+(?:to\s+|of\s+)?(\d{1,5})/i)||segment.match(/extended geoguessr streak to\s+(\d{1,5})/i);if(streak) out.push(trackerDetection('geoguessr-10k',date,1,segment,{value:Number(streak[1])}));
    if(/daily challenge/i.test(segment)){if(/lost|missed|broke|forgot|didn'?t|did not/.test(s)&&/streak|challenge/.test(s)) sawDailyMiss=true;if(/did|played|completed|finished|preserved|extended|beat|scored|got \d|daily challenge for/i.test(s)&&!/lost daily challenge|missed daily challenge|didn'?t do|did not do/.test(s)) sawDailyComplete=true;if(/monty/i.test(segment)){if(/beat|won|destroyed|demolished/i.test(segment)) out.push(trackerDetection('monty-dc',date,1,segment,{result:'win'}));else if(/lost|lose|lost to/i.test(segment)) out.push(trackerDetection('monty-dc',date,1,segment,{result:'loss'}))}}
  }
  if(sawDailyComplete) out.push(trackerDetection('daily-challenge',date,1,'Daily Challenge completed',{result:'complete'}));else if(sawDailyMiss) out.push(trackerDetection('daily-challenge',date,0,'Daily Challenge missed',{result:'miss'}));return dedupeDetections(out)
}
function dedupeDetections(items){const seen=new Map();for(const item of items){const key=`${item.trackerId}|${item.date}|${item.snippet}|${item.result||''}|${item.value||''}`;if(!seen.has(key))seen.set(key,item)}return [...seen.values()]}
export function replaceDetectedForDate(state,date,text){state.occurrences=(state.occurrences||[]).filter(x=>!(x.date===date&&x.source==='detected'));state.occurrences.push(...detectFromEntry(date,text))}
export function addManualOccurrence(state,{trackerId,date,count=1,result=null,value=null,snippet='Manual entry'}){state.occurrences.push({id:`manual:${cryptoId()}`,trackerId,date,count:Number(count)||0,result,value:value==null?null:Number(value),snippet,source:'manual'})}
export function cryptoId(){return (globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`)}
export function saveEntry(state,date,text){const now=new Date().toISOString();const previous=state.entries[date];const revisions=[...(previous?.revisions||[])];if(previous&&previous.text!==text) revisions.unshift({text:previous.text,savedAt:previous.updatedAt||now});state.entries[date]={text:String(text||'').trim(),updatedAt:now,revisions:revisions.slice(0,20)};replaceDetectedForDate(state,date,text);state.updatedAt=now;return state.entries[date]}
export function trackerDefinition(state,id){const base=DEFAULT_TRACKERS.find(x=>x.id===id)||{id,name:id,kind:'event',status:'intermittent',aliases:[id]};return {...base,...(state.trackerOverrides?.[id]||{})}}
export function allTrackerDefinitions(state){return DEFAULT_TRACKERS.map(t=>trackerDefinition(state,t.id))}
export function occurrencesFor(state,trackerId,{start=null,end=null,year=null,month=null}={}){let rows=(state.occurrences||[]).filter(x=>x.trackerId===trackerId);if(start)rows=rows.filter(x=>x.date>=start);if(end)rows=rows.filter(x=>x.date<=end);if(year)rows=rows.filter(x=>x.date.startsWith(`${year}-`));if(month)rows=rows.filter(x=>x.date.startsWith(month));return rows.sort((a,b)=>a.date.localeCompare(b.date))}
export function legacyTrackerTotal(state,trackerId,monthKey){const map=state.monthlyReviews?.[monthKey]?.trackerTotals||{};const v=map[trackerId];return Number.isFinite(Number(v))?Number(v):null}
export function trackerTotal(state,trackerId,scope={}){const rows=occurrencesFor(state,trackerId,scope);const raw=rows.reduce((n,x)=>n+(Number(x.count)||0),0);if(scope.month){const legacy=legacyTrackerTotal(state,trackerId,scope.month);return legacy==null?raw:Math.max(raw,legacy)}if(scope.year){let sum=0,hasLegacy=false;for(let m=1;m<=12;m++){const key=`${scope.year}-${String(m).padStart(2,'0')}`;const v=legacyTrackerTotal(state,trackerId,key);if(v!=null){sum+=v;hasLegacy=true}else sum+=occurrencesFor(state,trackerId,{month:key}).reduce((n,x)=>n+(Number(x.count)||0),0)}return hasLegacy?sum:raw}return raw}
export function dailyChallengeStreaks(state){const rows=occurrencesFor(state,'daily-challenge').filter(x=>x.result==='complete');const dates=[...new Set(rows.map(x=>x.date))].sort();if(!dates.length)return {current:0,longest:0,currentStart:null,longestStart:null,longestEnd:null,active:false};let longest=1,longestStart=dates[0],longestEnd=dates[0],run=1,runStart=dates[0];for(let i=1;i<dates.length;i++){if(shiftDay(dates[i-1],1)===dates[i])run++;else{run=1;runStart=dates[i]}if(run>longest){longest=run;longestStart=runStart;longestEnd=dates[i]}}let current=1,currentStart=dates.at(-1);for(let i=dates.length-1;i>0;i--){if(shiftDay(dates[i-1],1)===dates[i]){current++;currentStart=dates[i-1]}else break}const today=isoToday();const last=dates.at(-1);const active=last===today||last===shiftDay(today,-1);return {current:active?current:0,longest,currentStart:active?currentStart:null,longestStart,longestEnd,active,lastCompleted:last}}
export function geoguessr10kRecord(state){const rows=occurrencesFor(state,'geoguessr-10k').filter(x=>Number.isFinite(Number(x.value)));if(!rows.length)return null;return rows.reduce((best,x)=>Number(x.value)>Number(best.value)?x:best,rows[0])}
export function montyRecord(state,scope={}){const rows=occurrencesFor(state,'monty-dc',scope);return {wins:rows.filter(x=>x.result==='win').length,losses:rows.filter(x=>x.result==='loss').length}}
export function normalizedActivity(segment){const s=segment.toLowerCase();if(/edit|capcut|premiere|v\s?gc/.test(s))return 'Editing';if(/geoguessr/.test(s))return 'Geoguessr';if(/youtube|treyton|jomboy|poof|dashie|linus/.test(s))return 'YouTube / Videos';if(/shower|got dressed|hygiene|brushed teeth|shaved/.test(s))return 'Hygiene / Getting Ready';if(/ate|breakfast|lunch|dinner|dessert|food|doordash|culvers/.test(s))return 'Eating';if(/gta|crew|roblox|vr |vr$|playstation|ps5|switch|xbox|forza|game/.test(s))return 'Gaming';if(/yankees|knicks|giants|nascar|football|baseball|basketball|world cup|sports/.test(s))return 'Watching Sports';if(/laundry|clean|dishes|trash|vacuum|organize/.test(s))return 'Chores / Cleaning';if(/call|facetime|discord|cord|talked to|spoke to/.test(s))return 'Calls / Social';if(/sleep|fell asleep|nap|went to bed/.test(s))return 'Sleep';if(/woke up|got up/.test(s))return 'Morning Routine';return null}
export function activityStats(state,{year=null,month=null}={}){const counts=new Map(),daily=new Map();for(const [date,entry] of Object.entries(state.entries||{})){if(year&&!date.startsWith(`${year}-`))continue;if(month&&!date.startsWith(month))continue;for(const seg of splitEvents(entry.text)){const a=normalizedActivity(seg);if(!a)continue;counts.set(a,(counts.get(a)||0)+1);const k=`${date}|${a}`;daily.set(k,(daily.get(k)||0)+1)}}const sorted=[...counts.entries()].sort((a,b)=>b[1]-a[1]);return {counts:sorted,daily}}
export function mostActivityDay(state,activity='Editing',{year=null,month=null}={}){let best=null;for(const [date,entry] of Object.entries(state.entries||{})){if(year&&!date.startsWith(`${year}-`))continue;if(month&&!date.startsWith(month))continue;const count=splitEvents(entry.text).filter(s=>normalizedActivity(s)===activity).length;if(count&&(!best||count>best.count))best={date,count}}return best}
export function buildStory(text,{maxEvents=30}={}){const events=splitEvents(text).slice(0,maxEvents);if(!events.length)return 'No diary entry was saved for this day.';const clean=events.map((e,i)=>{let s=e.trim().replace(/\s+/g,' ').replace(/^I\s+/i,'you ').replace(/^my\s+/i,'your ');s=s.charAt(0).toLowerCase()+s.slice(1);if(i===0&&/^woke up/i.test(s))return 'You woke up';if(/^got up/i.test(s))return 'you got up'+s.slice(6);return (/^(you|your)\b/i.test(s)?s:`you ${s}`)});const sentences=[];for(let i=0;i<clean.length;i+=3){const group=clean.slice(i,i+3);let body=group.length===1?group[0]:group.length===2?`${group[0]} and ${group[1]}`:`${group[0]}, ${group[1]}, and ${group[2]}`;body=body.replace(/^you /,'You ');const lead=i===0?'':i<6?'Later, ':i<12?'After that, ':'As the day continued, ';sentences.push(`${lead}${body}.`)}return sentences.join(' ')}
export function daySummary(text){const events=splitEvents(text);if(!events.length)return 'No entry saved.';const important=events.filter(x=>/[A-Z]{4,}|birthday|graduat|finished|won|lost|first|final|historic|record|champion/i.test(x));return (important.length?important:events).slice(0,3).join(' · ')}
export function saveMonthlyReview(state,monthKey,{bestDay='',worstDay='',trackerTotals=null}={}){const prev=state.monthlyReviews[monthKey]||{};state.monthlyReviews[monthKey]={...prev,bestDay:bestDay||prev.bestDay||'',worstDay:worstDay||prev.worstDay||'',...(trackerTotals?{trackerTotals:{...(prev.trackerTotals||{}),...trackerTotals}}:{}),updatedAt:new Date().toISOString()};state.updatedAt=new Date().toISOString()}
export function saveYearlyReview(state,year,patch){state.yearlyReviews[year]={...(state.yearlyReviews[year]||{}),...patch,updatedAt:new Date().toISOString()};state.updatedAt=new Date().toISOString()}
export function loggingStreak(state){const dates=Object.entries(state.entries||{}).filter(([,e])=>e.text?.trim()).map(([d])=>d).sort();if(!dates.length)return {longest:0,current:0};let longest=1,run=1;for(let i=1;i<dates.length;i++){run=shiftDay(dates[i-1],1)===dates[i]?run+1:1;longest=Math.max(longest,run)}let current=1;for(let i=dates.length-1;i>0;i--){if(shiftDay(dates[i-1],1)===dates[i])current++;else break}return {longest,current,last:dates.at(-1)}}
export function scopedDates(state,{year=null,month=null}={}){return Object.keys(state.entries||{}).filter(d=>(!year||d.startsWith(`${year}-`))&&(!month||d.startsWith(month))).sort()}
export function findRelevantSnippets(text,needle){const terms=String(needle||'').toLowerCase().split(/\s+/).filter(x=>x.length>2);return splitEvents(text).filter(e=>terms.some(t=>e.toLowerCase().includes(t))).slice(0,4)}
export function scopeFromQuestion(q,now=isoToday()){const lower=q.toLowerCase();const yearMatch=lower.match(/\b(20\d{2})\b/);let year=yearMatch?Number(yearMatch[1]):null;let month=null;for(const [name,num] of Object.entries(MONTH_LOOKUP)){if(new RegExp(`\\b${name.slice(0,3)}(?:${name.slice(3)})?\\b`,'i').test(lower)){const y=year||Number(now.slice(0,4));month=`${y}-${String(num).padStart(2,'0')}`;break}}if(/this year/.test(lower))year=Number(now.slice(0,4));if(/this month/.test(lower))month=now.slice(0,7);return {year,month}}
export function trackerFromQuestion(state,q){const lower=q.toLowerCase();return allTrackerDefinitions(state).find(t=>[t.name,...(t.aliases||[])].some(a=>lower.includes(a.toLowerCase())))||null}
export function askTide(state,question){const q=String(question||'').trim();if(!q)return {type:'empty',primary:'Ask me something about your T.I.D.E. history.'};const lower=q.toLowerCase(),scope=scopeFromQuestion(q);const tracker=trackerFromQuestion(state,q);const scopeRowsOpts=scope.month?{month:scope.month}:scope.year?{year:scope.year}:{};
  if(tracker){const rows=occurrencesFor(state,tracker.id,scopeRowsOpts);const total=trackerTotal(state,tracker.id,scopeRowsOpts);if(/what months|which months/.test(lower)){const months=[...new Set(rows.map(x=>x.date.slice(0,7)))];return {type:'list',primary:months.length?`${months.length} month${months.length===1?'':'s'}`:'No matching months',items:months.map(monthLabel),detail:`Months with ${tracker.name.toLowerCase()}${scope.year?` in ${scope.year}`:''}.`}}if(/what years|which years/.test(lower)){const years=[...new Set(rows.map(x=>x.date.slice(0,4)))];return {type:'list',primary:years.length?`${years.length} year${years.length===1?'':'s'}`:'No matching years',items:years,detail:`Years with ${tracker.name.toLowerCase()}.`}}if(/what days|which days|what dates|which dates|when did/.test(lower)){const grouped=new Map();for(const r of rows)grouped.set(r.date,(grouped.get(r.date)||0)+(r.count||1));const items=[...grouped.entries()].map(([date,count])=>({date,label:dateLabel(date,{weekday:false}),meta:count>1?`${count} occurrences`:''}));return {type:'dates',primary:`${total} ${tracker.name.toLowerCase()}`,items,detail:`${items.length} distinct day${items.length===1?'':'s'}${scope.year?` in ${scope.year}`:''}.`}}if(/last|most recent/.test(lower)){const r=rows.at(-1);return {type:'date',primary:r?dateLabel(r.date,{weekday:false}):'No matching occurrence',date:r?.date,detail:r?.snippet||''}}if(/first/.test(lower)){const r=rows[0];return {type:'date',primary:r?dateLabel(r.date,{weekday:false}):'No matching occurrence',date:r?.date,detail:r?.snippet||''}}return {type:'count',primary:`${total}`,detail:`${tracker.name}${scope.month?` in ${monthLabel(scope.month)}`:scope.year?` in ${scope.year}`:' all time'}.`,items:rows.slice(-6).map(r=>({date:r.date,label:dateLabel(r.date,{weekday:false}),meta:r.snippet}))}}
  if(/what happened|on this day/.test(lower)){const m=lower.match(/\b(20\d{2})-(\d{2})-(\d{2})\b/);let date=m?m[0]:null;if(!date){const named=lower.match(new RegExp(`(${MONTHS.join('|')})\\s+(\\d{1,2})(?:st|nd|rd|th)?(?:,?\\s*(20\\d{2}))?`,'i'));if(named){const mo=MONTH_LOOKUP[named[1].toLowerCase()];date=`${named[3]||isoToday().slice(0,4)}-${String(mo).padStart(2,'0')}-${String(Number(named[2])).padStart(2,'0')}`}}if(date&&state.entries[date]?.text)return {type:'story',primary:dateLabel(date),date,detail:buildStory(state.entries[date].text)}}
  if(/why/.test(lower)){for(const [month,review] of Object.entries(state.monthlyReviews||{})){for(const [key,label] of [['bestDay','best'],['worstDay','worst']]){if(review[key]&&state.entries[review[key]]&&lower.includes(label)){return {type:'why',primary:`Why ${dateLabel(review[key],{weekday:false})} was your ${label} day`,date:review[key],detail:`You selected this as the ${label} day of ${monthLabel(month)}. Based on what you recorded that day: ${buildStory(state.entries[review[key]].text,{maxEvents:18})}`}}}}return {type:'why',primary:'I need a saved Best/Worst selection to explain that.',detail:'T.I.D.E. will explain from your own recorded events and will not invent a reason.'}}
  if(/edit/.test(lower)&&/(most|how many|what day|which day)/.test(lower)){const best=mostActivityDay(state,'Editing',scope);if(/most|what day|which day/.test(lower))return {type:'date',primary:best?dateLabel(best.date,{weekday:false}):'No editing day found',date:best?.date,detail:best?`${best.count} separate editing-related events were recognized in that entry.`:''};const stats=activityStats(state,scope);const total=stats.counts.find(([k])=>k==='Editing')?.[1]||0;return {type:'count',primary:String(total),detail:'Editing-related events recognized in the requested period.'}}
  if(/most common action|most done action|did the most/.test(lower)){const s=activityStats(state,scope).counts[0];return {type:'count',primary:s?s[0]:'No activity data',detail:s?`${s[1]} recognized events in the requested period.`:''}}
  const stop=new Set(['what','when','where','which','show','every','days','times','did','have','with','that','this','were','from','year','month','most','many','the','and','for','all','me','my','i']);const terms=lower.replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2&&!stop.has(x));const matches=[];for(const [date,entry] of Object.entries(state.entries||{})){if(scope.year&&!date.startsWith(`${scope.year}-`))continue;if(scope.month&&!date.startsWith(scope.month))continue;const snippets=findRelevantSnippets(entry.text,terms.join(' '));if(snippets.length)matches.push({date,label:dateLabel(date,{weekday:false}),meta:snippets.join(' · ')})}if(matches.length)return {type:'dates',primary:`${matches.length} matching day${matches.length===1?'':'s'}`,items:matches.slice(0,100),detail:`Matched: ${terms.join(', ')}`};return {type:'none',primary:'No matching T.I.D.E. data yet.',detail:'Try asking about a tracker, an activity, a date, a month, or a year. The search only uses what you have actually recorded.'}}
export function parseDateText(value,monthKey){if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const [y,m]=monthKey.split('-').map(Number);const n=Number(String(value).match(/\d{1,2}/)?.[0]);if(!n||n<1||n>daysInMonth(monthKey))return '';return `${y}-${String(m).padStart(2,'0')}-${String(n).padStart(2,'0')}`}
export function parseNotesImport(raw,state){const text=String(raw||'').replace(/\r/g,'');const lines=text.split('\n');let currentYear=null,currentMonth=null;let imported=0,monthly=0;let pendingDate=null,pending=[];const flush=()=>{if(!pendingDate)return;const body=pending.join(' ').trim();if(body){saveEntry(state,pendingDate,body);imported++}pendingDate=null;pending=[]};const dateRe=new RegExp(`^(${MONTHS.join('|')})\\s+(\\d{1,2})(?:st|nd|rd|th)?(?:,?\\s*(20\\d{2}))?\\s*-\\s*(.*)$`,'i');for(const rawLine of lines){const line=rawLine.replace(/^\*+|\*+$/g,'').trim();if(!line)continue;const yearOnly=line.match(/^20\d{2}$/);if(yearOnly){flush();currentYear=Number(line);continue}const monthOnly=MONTHS.find(m=>line.toLowerCase()===m.toLowerCase());if(monthOnly){flush();currentMonth=MONTH_LOOKUP[monthOnly.toLowerCase()];continue}const dm=line.match(dateRe);if(dm){flush();currentMonth=MONTH_LOOKUP[dm[1].toLowerCase()];currentYear=Number(dm[3]||currentYear||isoToday().slice(0,4));pendingDate=`${currentYear}-${String(currentMonth).padStart(2,'0')}-${String(Number(dm[2])).padStart(2,'0')}`;pending=[dm[4]||''];continue}const best=line.match(/^Best Day of the Month:\s*(.*)$/i);const worst=line.match(/^Worst Day of the Month:\s*(.*)$/i);if((best||worst)&&currentYear&&currentMonth){flush();const mk=`${currentYear}-${String(currentMonth).padStart(2,'0')}`;const v=(best||worst)[1];const date=parseDateText(v,mk);saveMonthlyReview(state,mk,{[best?'bestDay':'worstDay']:date});monthly++;continue}const summaryMap=[['mors-mutual',/^Mors Mutual Calls:\s*(.*)$/i],['migraines',/^Migraines:\s*(.*)$/i],['google-car',/^GTA Google Car Casualties:\s*(.*)$/i],['apartment-collisions',/^Times I walked into an object.*?:\s*(.*)$/i]];let handled=false;for(const [id,re] of summaryMap){const mt=line.match(re);if(mt&&currentYear&&currentMonth){flush();const n=Number(mt[1].match(/\d+/)?.[0]);if(Number.isFinite(n)){const mk=`${currentYear}-${String(currentMonth).padStart(2,'0')}`;saveMonthlyReview(state,mk,{trackerTotals:{[id]:n}})}handled=true;break}}if(handled)continue;if(pendingDate)pending.push(line)}flush();state.rawImports.push({id:cryptoId(),importedAt:new Date().toISOString(),characters:text.length});return {entries:imported,monthlyFields:monthly}}
