import * as base from './engine.js?base=1';
export * from './engine.js?base=1';

const n=v=>Number.isFinite(Number(v))?Number(v):null;
const monthEnd=month=>base.monthBounds(month).end;
const todayForMonth=month=>{const today=base.isoToday();return today.startsWith(`${month}-`)?today:monthEnd(month)};
const monthKeys=(state,trackerId=null)=>{const keys=new Set(Object.keys(state.monthlyReviews||{}));for(const row of state.occurrences||[])if(!trackerId||row.trackerId===trackerId)keys.add(row.date.slice(0,7));return [...keys].sort()};
const rawMonth=(state,id,month)=>base.occurrencesFor(state,id,{month}).reduce((sum,x)=>sum+(Number(x.count)||0),0);

export function addManualOccurrence(state,{trackerId,date,count=1,result=null,value=null,snippet='Manual entry',myScore=null,opponentScore=null,metadata={}}){
  state.occurrences||=[];state.occurrences.push({id:`manual:${base.cryptoId()}`,trackerId,date,count:Number(count)||0,result,value:value==null?null:Number(value),snippet,source:'manual',myScore:myScore==null||myScore===''?null:Number(myScore),opponentScore:opponentScore==null||opponentScore===''?null:Number(opponentScore),...(metadata&&typeof metadata==='object'?metadata:{})});
}

export function saveMonthlyReview(state,monthKey,{bestDay='',worstDay='',trackerTotals=null,trackerSnapshots=null,cumulativeSnapshots=null,versusTotals=null}={}){
  const prev=state.monthlyReviews[monthKey]||{};state.monthlyReviews[monthKey]={...prev,bestDay:bestDay||prev.bestDay||'',worstDay:worstDay||prev.worstDay||'',...(trackerTotals?{trackerTotals:{...(prev.trackerTotals||{}),...trackerTotals}}:{}),...(trackerSnapshots?{trackerSnapshots:{...(prev.trackerSnapshots||{}),...trackerSnapshots}}:{}),...(cumulativeSnapshots?{cumulativeSnapshots:{...(prev.cumulativeSnapshots||{}),...cumulativeSnapshots}}:{}),...(versusTotals?{versusTotals:{...(prev.versusTotals||{}),...versusTotals}}:{}),updatedAt:new Date().toISOString()};state.updatedAt=new Date().toISOString();
}

export function trackerSnapshot(state,id,month){const x=state.monthlyReviews?.[month]?.trackerSnapshots?.[id];return x&&n(x.value)!=null?{...x,value:n(x.value)}:null}
export function cumulativeTrackerSnapshot(state,id,month){const x=state.monthlyReviews?.[month]?.cumulativeSnapshots?.[id];return x&&n(x.value)!=null?{...x,value:n(x.value)}:null}
export function legacyYearTrackerTotal(state,id,year){return n(state.yearlyReviews?.[year]?.trackerTotals?.[id])}
const authoritativeMonth=(state,id,month)=>{const raw=rawMonth(state,id,month),legacy=base.legacyTrackerTotal(state,id,month);return legacy==null?raw:Math.max(raw,legacy)};
const yearTotal=(state,id,year)=>{const keys=monthKeys(state,id).filter(k=>k.startsWith(`${year}-`));let total=keys.reduce((s,k)=>s+authoritativeMonth(state,id,k),0);const yr=legacyYearTrackerTotal(state,id,year);if(yr!=null)total=Math.max(total,yr);const cumulative=keys.map(k=>cumulativeTrackerSnapshot(state,id,k)).filter(Boolean);if(cumulative.length)total=Math.max(total,...cumulative.map(x=>x.value));return total};
export function trackerTotal(state,id,scope={}){if(scope.month)return authoritativeMonth(state,id,scope.month);if(scope.year)return yearTotal(state,id,scope.year);const years=new Set(monthKeys(state,id).map(k=>Number(k.slice(0,4))));for(const y of Object.keys(state.yearlyReviews||{}))if(legacyYearTrackerTotal(state,id,y)!=null)years.add(Number(y));let total=[...years].reduce((s,y)=>s+yearTotal(state,id,y),0);const cumulative=monthKeys(state,id).map(k=>cumulativeTrackerSnapshot(state,id,k)).filter(Boolean);if(cumulative.length)total=Math.max(total,...cumulative.map(x=>x.value));return total}
export function trackerMonthsWithData(state,id,{year=null}={}){return monthKeys(state,id).filter(k=>(!year||k.startsWith(`${year}-`))&&(authoritativeMonth(state,id,k)>0||cumulativeTrackerSnapshot(state,id,k)))}

const snapshots=(state,id)=>Object.entries(state.monthlyReviews||{}).map(([month,r])=>{const x=r?.trackerSnapshots?.[id];return x&&n(x.value)!=null?{month,...x,value:n(x.value)}:null}).filter(Boolean).sort((a,b)=>String(a.date||a.month).localeCompare(String(b.date||b.month)));
export function dailyChallengeStreaks(state){
  const dates=[...new Set(base.occurrencesFor(state,'daily-challenge').filter(x=>x.result==='complete').map(x=>x.date))].sort();let longest=0,longestStart=null,longestEnd=null,current=0,currentStart=null,lastCompleted=dates.at(-1)||null,active=false;
  if(dates.length){let run=1,runStart=dates[0];longest=1;longestStart=dates[0];longestEnd=dates[0];for(let i=1;i<dates.length;i++){if(base.shiftDay(dates[i-1],1)===dates[i])run++;else{run=1;runStart=dates[i]}if(run>longest){longest=run;longestStart=runStart;longestEnd=dates[i]}}current=1;currentStart=dates.at(-1);for(let i=dates.length-1;i>0;i--){if(base.shiftDay(dates[i-1],1)===dates[i]){current++;currentStart=dates[i-1]}else break}const today=base.isoToday();active=lastCompleted===today||lastCompleted===base.shiftDay(today,-1);if(!active){current=0;currentStart=null}}
  const snaps=snapshots(state,'daily-challenge');for(const x of snaps){if(x.value>longest){longest=x.value;longestEnd=x.date||monthEnd(x.month);longestStart=base.shiftDay(longestEnd,-(x.value-1))}}const latest=snaps.at(-1);if(latest){const d=latest.date||monthEnd(latest.month),today=base.isoToday(),snapActive=d===today||d===base.shiftDay(today,-1);if(snapActive&&latest.value>=current){current=latest.value;currentStart=base.shiftDay(d,-(latest.value-1));lastCompleted=d;active=true}}return{current,longest,currentStart,longestStart,longestEnd,active,lastCompleted};
}
export function geoguessr10kRecord(state){const rows=base.occurrencesFor(state,'geoguessr-10k').filter(x=>n(x.value)!=null).map(x=>({...x,value:n(x.value)}));const snaps=snapshots(state,'geoguessr-10k').map(x=>({trackerId:'geoguessr-10k',date:x.date||monthEnd(x.month),value:x.value,source:'snapshot',snippet:'Imported monthly snapshot'}));const all=[...rows,...snaps];return all.length?all.reduce((best,x)=>x.value>best.value?x:best,all[0]):null}
const rawMonty=(state,month)=>{const rows=base.occurrencesFor(state,'monty-dc',{month});return{wins:rows.filter(x=>x.result==='win').length,losses:rows.filter(x=>x.result==='loss').length,ties:rows.filter(x=>x.result==='tie').length}};
export function montyRecord(state,scope={}){const months=monthKeys(state,'monty-dc').filter(k=>!scope.month||k===scope.month).filter(k=>!scope.year||k.startsWith(`${scope.year}-`));let wins=0,losses=0,ties=0;for(const month of months){const raw=rawMonty(state,month),saved=state.monthlyReviews?.[month]?.versusTotals?.['monty-dc'];wins+=saved?Math.max(raw.wins,Number(saved.wins)||0):raw.wins;losses+=saved?Math.max(raw.losses,Number(saved.losses)||0):raw.losses;ties+=saved?Math.max(raw.ties,Number(saved.ties)||0):raw.ties}if(scope.year){const yr=state.yearlyReviews?.[scope.year]?.versusTotals?.['monty-dc'];if(yr){wins=Math.max(wins,Number(yr.wins)||0);losses=Math.max(losses,Number(yr.losses)||0);ties=Math.max(ties,Number(yr.ties)||0)}}return{wins,losses,ties}}
export function dailyChallengeScoreStats(state,{year=null}={}){const mine=base.occurrencesFor(state,'daily-challenge',year?{year}:{}).filter(x=>n(x.myScore)!=null).map(x=>({date:x.date,score:n(x.myScore)})),opp=base.occurrencesFor(state,'monty-dc',year?{year}:{}).filter(x=>n(x.opponentScore)!=null).map(x=>({date:x.date,score:n(x.opponentScore)}));const avg=a=>a.length?Math.round(a.reduce((s,x)=>s+x.score,0)/a.length):null,high=a=>a.length?a.reduce((b,x)=>x.score>b.score?x:b,a[0]):null;return{myAverage:avg(mine),opponentAverage:avg(opp),myHigh:high(mine),opponentHigh:high(opp)}}

export function askTide(state,question){
  const q=String(question||'').trim(),lower=q.toLowerCase(),scope=base.scopeFromQuestion(q),tracker=base.trackerFromQuestion(state,q),rowScope=scope.month?{month:scope.month}:scope.year?{year:scope.year}:{};
  if(tracker){const rows=base.occurrencesFor(state,tracker.id,rowScope),total=trackerTotal(state,tracker.id,rowScope);if(/what months|which months/.test(lower)){const months=trackerMonthsWithData(state,tracker.id,{year:scope.year});return{type:'list',primary:months.length?`${months.length} month${months.length===1?'':'s'}`:'No matching months',items:months.map(base.monthLabel),detail:`Months with ${tracker.name.toLowerCase()}${scope.year?` in ${scope.year}`:''}.`}}if(/what years|which years/.test(lower)){const years=[...new Set(trackerMonthsWithData(state,tracker.id).map(x=>x.slice(0,4)))];return{type:'list',primary:years.length?`${years.length} year${years.length===1?'':'s'}`:'No matching years',items:years,detail:`Years with ${tracker.name.toLowerCase()}.`}}if(/what days|which days|what dates|which dates|when did/.test(lower)){const grouped=new Map();for(const r of rows)grouped.set(r.date,(grouped.get(r.date)||0)+(r.count||1));const items=[...grouped].map(([date,count])=>({date,label:base.dateLabel(date,{weekday:false}),meta:count>1?`${count} occurrences`:''})),dated=[...grouped.values()].reduce((a,b)=>a+b,0),unknown=Math.max(0,total-dated);return{type:'dates',primary:`${total} ${tracker.name.toLowerCase()}`,items,detail:`${items.length} distinct recorded day${items.length===1?'':'s'}${scope.year?` in ${scope.year}`:''}.${unknown?` ${unknown} additional occurrence${unknown===1?'':'s'} are preserved only in older totals, so T.I.D.E. will not invent dates for them.`:''}`}}if(/last|most recent/.test(lower)){const r=rows.at(-1);return{type:'date',primary:r?base.dateLabel(r.date,{weekday:false}):'No matching occurrence',date:r?.date,detail:r?.snippet||''}}if(/first/.test(lower)){const r=rows[0];return{type:'date',primary:r?base.dateLabel(r.date,{weekday:false}):'No matching occurrence',date:r?.date,detail:r?.snippet||''}}return{type:'count',primary:String(total),detail:`${tracker.name}${scope.month?` in ${base.monthLabel(scope.month)}`:scope.year?` in ${scope.year}`:' all time'}.`,items:rows.slice(-6).map(r=>({date:r.date,label:base.dateLabel(r.date,{weekday:false}),meta:r.snippet}))}}
  if(/why/.test(lower)){const targetYear=scope.year||(/\bthis year\b/.test(lower)?Number(base.isoToday().slice(0,4)):null),yr=targetYear?state.yearlyReviews?.[targetYear]:null;if(yr){for(const [key,label] of [['bestDay','best'],['worstDay','worst']])if(lower.includes(label)&&/day/.test(lower)&&yr[key]&&state.entries[yr[key]])return{type:'why',primary:`Why ${base.dateLabel(yr[key],{weekday:false})} was your ${label} day of ${targetYear}`,date:yr[key],detail:`You selected this as your ${label} day of ${targetYear}. Based only on what you recorded: ${base.buildStory(state.entries[yr[key]].text,{maxEvents:20})}`};for(const [key,label] of [['bestMonth','best'],['worstMonth','worst']])if(lower.includes(label)&&/month/.test(lower)&&yr[key]){const mk=`${targetYear}-${String(yr[key]).padStart(2,'0')}`,stats=base.activityStats(state,{month:mk}).counts.slice(0,3),mr=state.monthlyReviews?.[mk]||{};return{type:'why',primary:`Why ${base.monthLabel(mk)} was your ${label} month`,detail:`You selected ${base.monthLabel(mk)} as your ${label} month. T.I.D.E. recorded ${base.scopedDates(state,{month:mk}).length} diary days${stats.length?`, led by ${stats.map(([a,c])=>`${a} (${c})`).join(', ')}`:''}${mr.bestDay?`. Your best day that month was ${base.dateLabel(mr.bestDay,{weekday:false})}`:''}. This describes your records without inventing a cause.`}}}}
  return base.askTide(state,q);
}

export function parseNotesImport(raw,state){
  const text=String(raw||'').replace(/\r/g,''),lines=text.split('\n');let currentYear=null,currentMonth=null,imported=0,monthly=0,pendingDate=null,pending=[],inYearReview=false,reviewYear=null,pendingYearLabel=null;
  const flush=()=>{if(!pendingDate)return;const body=pending.join(' ').trim();if(body&&pendingDate<=base.isoToday()){base.saveEntry(state,pendingDate,body);imported++}pendingDate=null;pending=[]};
  const monthKey=()=>currentYear&&currentMonth?`${currentYear}-${String(currentMonth).padStart(2,'0')}`:null;
  const saveLegacy=(label,value)=>{if(!reviewYear||!label)return;const clean=String(value??'').trim(),prev=state.yearlyReviews[reviewYear]||{},next={...prev,legacyFields:{...(prev.legacyFields||{}),[label]:clean},updatedAt:new Date().toISOString()},num=Number(clean.match(/-?\d[\d,]*/)?.[0]?.replaceAll(',','')),l=label.toLowerCase(),map=l.includes('mors mutual')?'mors-mutual':l.includes('google car casualties')?'google-car':l.includes('collision count')?'collision-count':l.includes('migraines')?'migraines':null;if(map&&Number.isFinite(num))next.trackerTotals={...(prev.trackerTotals||{}),[map]:num};if(l.includes(`${reviewYear} daily challenge record vs monty`)){const m=clean.match(/(\d+)\s*-\s*(\d+)/);if(m)next.versusTotals={...(prev.versusTotals||{}),'monty-dc':{wins:Number(m[1]),losses:Number(m[2]),ties:0}}}state.yearlyReviews[reviewYear]=next};
  const dateRe=new RegExp(`^(${base.MONTHS.join('|')})\\s+(\\d{1,2})(?:st|nd|rd|th)?(?:,?\\s*(20\\d{2}))?\\s*-\\s*(.*)$`,'i');
  for(const rawLine of lines){const line=rawLine.replace(/^\*+|\*+$/g,'').trim();if(!line)continue;const marker=line.match(/^(20\d{2})\s*-\s*YEAR IN REVIEW$/i);if(marker){flush();inYearReview=true;reviewYear=Number(marker[1]);currentYear=reviewYear;currentMonth=null;pendingYearLabel=null;continue}const yearOnly=line.match(/^20\d{2}$/);if(yearOnly&&!inYearReview){flush();currentYear=Number(line);continue}const mo=base.MONTHS.find(m=>line.toLowerCase()===m.toLowerCase());if(mo&&!inYearReview){flush();currentMonth=base.MONTH_LOOKUP[mo.toLowerCase()];continue}const dm=line.match(dateRe);if(dm){flush();inYearReview=false;pendingYearLabel=null;currentMonth=base.MONTH_LOOKUP[dm[1].toLowerCase()];currentYear=Number(dm[3]||currentYear||base.isoToday().slice(0,4));pendingDate=`${currentYear}-${String(currentMonth).padStart(2,'0')}-${String(Number(dm[2])).padStart(2,'0')}`;pending=[dm[4]||''];continue}
    if(inYearReview){if(/^(?:AVG\b|HIGHEST\b|Daily Challenge Streak Losses\b|ALL TIME Daily Challenge Streak Losses\b|ALL TIME Daily Challenge Record vs Monty:)/i.test(line)){pendingYearLabel=line.replace(/:\s*\(As of[^)]*\)\s*$/i,'').replace(/:\s*$/,'');continue}const inline=line.match(/^([^:]{3,120}:)\s*(.+)$/),blank=line.match(/^([^:]{3,120}:)\s*$/);if(inline){saveLegacy(inline[1].replace(/:$/,''),inline[2]);pendingYearLabel=null;continue}if(blank){pendingYearLabel=blank[1].replace(/:$/,'');continue}if(pendingYearLabel&&!/^(ODDITIES|GEOGUESSR|MUSIC|OVERALL|20\d{2}\s*-\s*MUSIC YEAR IN REVIEW)$/i.test(line)){saveLegacy(pendingYearLabel,line);pendingYearLabel=null}continue}
    const best=line.match(/^Best Day of the Month:\s*(.*)$/i),worst=line.match(/^Worst Day of the Month:\s*(.*)$/i);if((best||worst)&&currentYear&&currentMonth){flush();const mk=monthKey(),date=base.parseDateText((best||worst)[1],mk);saveMonthlyReview(state,mk,{[best?'bestDay':'worstDay']:date});monthly++;continue}
    const summaries=[['mors-mutual',/^Mors Mutual Calls:\s*(.*)$/i],['migraines',/^Migraines:\s*(.*)$/i],['google-car',/^GTA Google Car Casualties:\s*(.*)$/i],['collision-count',/^Collision Count:\s*(.*)$/i],['apartment-collisions',/^Times I walked into an object.*?:\s*(.*)$/i]];let handled=false;for(const [id,re] of summaries){const m=line.match(re);if(m&&currentYear&&currentMonth){flush();const value=Number(m[1].match(/\d+/)?.[0]);if(Number.isFinite(value))saveMonthlyReview(state,monthKey(),{trackerTotals:{[id]:value}});handled=true;break}}if(handled)continue;
    const hk=line.match(/^Hong Kong Spawns \(All Time\):\s*(.*)$/i);if(hk&&currentYear&&currentMonth){flush();const value=Number(hk[1].match(/\d+/)?.[0]);if(Number.isFinite(value)){const mk=monthKey();saveMonthlyReview(state,mk,{cumulativeSnapshots:{'hong-kong':{value,date:todayForMonth(mk)}}})}continue}
    const tenk=line.match(/^Geoguessr 10K Streak:\s*(.*)$/i);if(tenk&&currentYear&&currentMonth){flush();const value=Number(tenk[1].match(/\d+/)?.[0]);if(Number.isFinite(value)){const mk=monthKey();saveMonthlyReview(state,mk,{trackerSnapshots:{'geoguessr-10k':{value,date:todayForMonth(mk)}}})}continue}
    const dc=line.match(/^Current Daily Challenge Streak:\s*(.*)$/i);if(dc&&currentYear&&currentMonth){flush();const value=Number(dc[1].match(/\d+/)?.[0]);if(Number.isFinite(value)){const mk=monthKey();saveMonthlyReview(state,mk,{trackerSnapshots:{'daily-challenge':{value,date:todayForMonth(mk)}}})}continue}
    const vs=line.match(/^(?:January|February|March|April|May|June|July|August|September|October|November|December) Daily Challenge Record vs Monty:\s*(\d+)\s*-\s*(\d+)/i);if(vs&&currentYear&&currentMonth){flush();saveMonthlyReview(state,monthKey(),{versusTotals:{'monty-dc':{wins:Number(vs[1]),losses:Number(vs[2]),ties:0}}});continue}if(pendingDate)pending.push(line);
  }
  flush();state.rawImports||=[];state.rawImports.push({id:base.cryptoId(),importedAt:new Date().toISOString(),characters:text.length});return{entries:imported,monthlyFields:monthly};
}
