import {dailyChallengeCounter,ensureSimpleCounters,incrementDailyChallenge,isoToday,markDailyChallengeMissed,montyRecord,recordMontyResult,setDailyChallengeStreak,setMonthlyMontyBaseline,setMontyOverall,trackerTotal} from './engine-v3.js';
const KEY='tide_state_v1',root=document.querySelector('#view-root');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const load=()=>{try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(!s)return null;ensureSimpleCounters(s);localStorage.setItem(KEY,JSON.stringify(s));return s}catch{return null}};
const save=s=>{ensureSimpleCounters(s);s.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(s)};
const card=(l,v,d='')=>`<div class="record-card"><div class="stat-label">${esc(l)}</div><div class="record-value">${esc(v)}</div>${d?`<div class="record-detail">${esc(d)}</div>`:''}</div>`;
function selectedDay(){const t=root.querySelector('.day-nav-center h1')?.textContent?.trim();if(!t)return null;const d=new Date(`${t.replace(/^[A-Za-z]+,\s*/,'')} 12:00:00`);return Number.isNaN(d.getTime())?null:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function enhanceToday(){
  if(document.querySelector('#tide-simple-live')||!root.querySelector('#day-editor'))return;const s=load(),date=selectedDay();if(!s||!date)return;
  const today=isoToday(),isToday=date===today,c=dailyChallengeCounter(s),month=today.slice(0,7),m=montyRecord(s,{month}),all=montyRecord(s),sec=document.createElement('section');sec.id='tide-simple-live';sec.className='card';
  sec.innerHTML=`<div class="card-header"><div><h3>GeoGuessr</h3><div class="small muted">Manual counters only. No score entry, no ties, no automatic Daily Challenge counting.</div></div><span class="chip accent">LIVE</span></div><div style="text-align:center;padding:6px 0 14px"><div class="stat-label">DAILY CHALLENGE STREAK</div><div class="big-stat" style="font-size:60px;line-height:1.05;margin-top:6px">${c.value}</div></div>${isToday?`<button id="simple-dc-plus" class="button primary" style="width:100%;font-size:18px;padding:14px">↑ +1 Daily Challenge</button><div class="tiny subtle" style="margin-top:7px;text-align:center">Click once whenever you want to advance the streak. There is no date or 8 PM logic.</div>`:`<div class="callout">Live counters can only be changed from Today.</div>`}<div class="section-title">VS MONTY</div><div class="grid grid-2" style="margin-bottom:12px">${card('This Month',`${m.wins}-${m.losses}`,month)}${card('All Time',`${all.wins}-${all.losses}`,'Keeps running across months')}</div>${isToday?`<div class="grid grid-2"><button id="simple-monty-win" class="button primary" style="font-size:16px;padding:12px">I Beat Monty · WIN</button><button id="simple-monty-loss" class="button" style="font-size:16px;padding:12px">Monty Beat Me · LOSS</button></div><div class="tiny subtle" style="margin-top:7px;text-align:center">A new month starts at 0-0. All Time keeps going.</div>`:''}`;
  (root.querySelector('.right-stack')||root).prepend(sec);const plus=sec.querySelector('#simple-dc-plus'),win=sec.querySelector('#simple-monty-win'),loss=sec.querySelector('#simple-monty-loss');
  if(plus)plus.onclick=()=>{const x=load();if(!x)return;incrementDailyChallenge(x);save(x);location.reload()};if(win)win.onclick=()=>{const x=load();if(!x)return;recordMontyResult(x,'win');save(x);location.reload()};if(loss)loss.onclick=()=>{const x=load();if(!x)return;recordMontyResult(x,'loss');save(x);location.reload()};
}
function enhanceMonthly(){
  if(document.querySelector('#tide-simple-month'))return;const sel=root.querySelector('#month-select');if(!sel)return;const month=sel.value,s=load();if(!s)return;const r=montyRecord(s,{month}),sec=document.createElement('section');sec.id='tide-simple-month';sec.className='card';sec.style.marginTop='16px';
  sec.innerHTML=`<div class="card-header"><div><h2>Daily Challenge vs Monty</h2><div class="small muted">Win-loss only. Each calendar month has its own record.</div></div><span class="chip accent">${r.wins}-${r.losses}</span></div><div class="grid grid-2">${card('Wins',r.wins)}${card('Losses',r.losses)}</div><div class="section-title">CORRECT THIS MONTH ONLY</div><div class="grid grid-2"><label class="label">Wins<input id="simple-month-w" class="input" type="number" min="0" value="${r.wins}"></label><label class="label">Losses<input id="simple-month-l" class="input" type="number" min="0" value="${r.losses}"></label></div><button id="simple-month-save" class="button" style="margin-top:10px">Save Month Record</button>`;root.append(sec);sec.querySelector('#simple-month-save').onclick=()=>{const x=load();if(!x)return;setMonthlyMontyBaseline(x,month,{wins:sec.querySelector('#simple-month-w').value,losses:sec.querySelector('#simple-month-l').value});save(x);location.reload()};
}
function enhanceYear(){
  if(document.querySelector('#tide-v2-year-details'))return;const t=root.querySelector('.page-head h1')?.textContent||'',m=t.match(/^(20\d{2})\s*·\s*Year in Review/);if(!m)return;const y=Number(m[1]),s=load();if(!s)return;const review=s.yearlyReviews?.[y]||{},legacy=review.legacyFields||{},mr=montyRecord(s,{year:y}),dc=dailyChallengeCounter(s),sec=document.createElement('div');sec.id='tide-v2-year-details';
  sec.innerHTML=`<div class="section-title">T.I.D.E. DETAIL RECORDS</div><section class="card"><div class="card-header"><div><h2>Full Year-Review Detail</h2><div class="small muted">Monty is W-L only. Daily Challenge is a manual streak counter.</div></div><span class="chip accent">LIVE</span></div><div class="records-grid">${card('Google Car Casualties',trackerTotal(s,'google-car',{year:y}))}${card('Collision Count',trackerTotal(s,'collision-count',{year:y}))}${card('Daily Challenge vs Monty',`${mr.wins}-${mr.losses}`,'W-L')}${card('Current DC Streak',dc.value)}</div><div class="section-title">MUSIC DETAIL</div><div class="filter-row"><label class="label" style="flex:1">Final Song of ${y}<input id="v2-final-song" class="input" style="width:100%" value="${esc(review.finalSong||legacy[`FINAL SONG OF ${y}`]||'')}" placeholder="Save the final song of the year"></label><button id="v2-save-final" class="button primary">Save Final Song</button></div>${Object.keys(legacy).length?`<div class="section-title">PRESERVED FROM ORIGINAL YEAR IN REVIEW</div><div class="tracker-table">${Object.entries(legacy).map(([k,v])=>`<div class="detected-item"><span>${esc(k)}</span><b>${esc(v||'—')}</b></div>`).join('')}</div>`:''}</section>`;const h=[...root.querySelectorAll('.section-title')].find(x=>/MUSIC YEAR IN REVIEW/i.test(x.textContent));if(h)h.before(sec);else root.append(sec);sec.querySelector('#v2-save-final').onclick=()=>{const x=load();if(!x)return;x.yearlyReviews||={};x.yearlyReviews[y]={...(x.yearlyReviews[y]||{}),finalSong:sec.querySelector('#v2-final-song').value.trim(),updatedAt:new Date().toISOString()};save(x)};
}
function enhanceTrackers(){
  if(document.querySelector('#tide-simple-controls'))return;if((root.querySelector('.page-head h1')?.textContent||'')!=='Trackers')return;const s=load();if(!s)return;const c=dailyChallengeCounter(s),month=isoToday().slice(0,7),m=montyRecord(s,{month}),all=montyRecord(s),sec=document.createElement('section');sec.id='tide-simple-controls';sec.className='card';sec.style.marginBottom='16px';
  sec.innerHTML=`<div class="card-header"><div><h2>GeoGuessr Controls</h2><div class="small muted">Manual counters only. These are the authoritative values.</div></div><span class="chip accent">SIMPLE</span></div><div class="records-grid">${card('Daily Challenge Streak',c.value)}${card('Monty This Month',`${m.wins}-${m.losses}`)}${card('Monty All Time',`${all.wins}-${all.losses}`)}</div><div class="filter-row" style="margin-top:14px"><button id="simple-track-plus" class="button primary">↑ +1 Daily Challenge</button><button id="simple-track-reset" class="button ghost">Streak Lost / Reset</button></div><div class="section-title">CORRECT DAILY CHALLENGE</div><div class="filter-row"><input id="simple-dc-set-value" class="input" type="number" min="0" value="${c.value}" style="max-width:180px"><button id="simple-dc-set" class="button">Set Streak</button></div><div class="section-title">CORRECT ALL-TIME MONTY RECORD</div><div class="grid grid-2"><label class="label">Wins<input id="simple-all-w" class="input" type="number" min="0" value="${all.wins}"></label><label class="label">Losses<input id="simple-all-l" class="input" type="number" min="0" value="${all.losses}"></label></div><button id="simple-all-save" class="button" style="margin-top:10px">Set All-Time Record</button>`;const first=root.querySelector(':scope > .card');if(first)first.before(sec);else root.append(sec);
  sec.querySelector('#simple-track-plus').onclick=()=>{const x=load();if(!x)return;incrementDailyChallenge(x);save(x);location.reload()};sec.querySelector('#simple-track-reset').onclick=()=>{if(!confirm('Reset the current Daily Challenge streak to 0?'))return;const x=load();if(!x)return;markDailyChallengeMissed(x);save(x);location.reload()};sec.querySelector('#simple-dc-set').onclick=()=>{const x=load();if(!x)return;setDailyChallengeStreak(x,sec.querySelector('#simple-dc-set-value').value);save(x);location.reload()};sec.querySelector('#simple-all-save').onclick=()=>{const x=load();if(!x)return;setMontyOverall(x,{wins:sec.querySelector('#simple-all-w').value,losses:sec.querySelector('#simple-all-l').value});save(x);location.reload()};
}
let pending=false;const run=()=>{pending=false;enhanceToday();enhanceMonthly();enhanceYear();enhanceTrackers()};new MutationObserver(()=>{if(pending)return;pending=true;queueMicrotask(run)}).observe(root,{childList:true,subtree:true});run();