const KEY='tide_state_v1';
const REPAIR='geo-final-one-deploy-v1';
const BASE_DATE='2026-08-23';
const START_DATE='2026-04-28';
const INITIAL_STREAK=118;
const INITIAL_MONTH='2026-08';
const INITIAL_OVERALL={wins:28,losses:103};
const root=document.querySelector('#view-root');
const now=()=>new Date().toISOString();
const today=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`};
const shift=(date,n)=>{const [y,m,d]=date.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const short=d=>d?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${d}T12:00:00`)):'—';
const cleanRecord=r=>({wins:Math.max(0,Number(r?.wins)||0),losses:Math.max(0,Number(r?.losses)||0)});
const card=(l,v,d='')=>`<div class="record-card"><div class="stat-label">${esc(l)}</div><div class="record-value">${esc(v)}</div>${d?`<div class="record-detail">${esc(d)}</div>`:''}</div>`;

function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{version:1,entries:{},monthlyReviews:{},yearlyReviews:{},occurrences:[],settings:{}}}catch{return{version:1,entries:{},monthlyReviews:{},yearlyReviews:{},occurrences:[],settings:{}}}}
function write(s){s.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(s))}
function ensureShape(s){s.settings||={};s.settings.migrations||={};s.monthlyReviews||={};s.yearlyReviews||={};s.occurrences||=[];s.tideCounters||={};s.tideCounters.montyYears||={};return s}
function monthRecord(s,month=today().slice(0,7)){ensureShape(s);return cleanRecord(s.monthlyReviews?.[month]?.versusTotals?.['monty-dc'])}
function overallRecord(s){ensureShape(s);return cleanRecord(s.tideCounters.montyOverall||INITIAL_OVERALL)}
function streak(s){ensureShape(s);const d=s.tideCounters.dailyChallenge||{};return{current:Math.max(0,Number(d.current)||0),longest:Math.max(0,Number(d.longest)||0),start:d.currentStart||null,last:d.lastCounted||null,longestStart:d.longestStart||null,longestEnd:d.longestEnd||null}}

function repair(s){
  ensureShape(s);
  if(s.settings.migrations[REPAIR])return false;
  s.tideCounters.dailyChallenge={current:INITIAL_STREAK,longest:INITIAL_STREAK,currentStart:START_DATE,lastCounted:BASE_DATE,longestStart:START_DATE,longestEnd:BASE_DATE,updatedAt:now()};
  s.tideCounters.montyOverall={...INITIAL_OVERALL,updatedAt:now()};
  s.tideCounters.montyYears[2026]={...INITIAL_OVERALL,updatedAt:now()};
  const aug=s.monthlyReviews[INITIAL_MONTH]||{};
  s.monthlyReviews[INITIAL_MONTH]={...aug,versusTotals:{...(aug.versusTotals||{}),'monty-dc':{wins:0,losses:3,ties:0}},updatedAt:now()};
  s.occurrences=s.occurrences.filter(r=>!(r.trackerId==='daily-challenge'&&r.date>=START_DATE&&r.date<=BASE_DATE));
  for(let i=0;i<INITIAL_STREAK;i++){const date=shift(START_DATE,i);s.occurrences.push({id:`dc-final:${date}`,trackerId:'daily-challenge',date,count:1,result:'complete',source:'manual',logType:'dc-authoritative',snippet:'Daily Challenge completed',createdAt:now()})}
  s.occurrences=s.occurrences.filter(r=>!(r.trackerId==='monty-dc'&&r.date?.startsWith('2026-08')));
  s.settings.migrations[REPAIR]=true;
  write(s);
  return true;
}

function plusOne(){const s=ensureShape(read()),d=streak(s),date=today();if(d.current===0)d.start=date;d.current++;d.last=date;if(d.current>d.longest){d.longest=d.current;d.longestStart=d.start;d.longestEnd=date}s.tideCounters.dailyChallenge={current:d.current,longest:d.longest,currentStart:d.start,lastCounted:d.last,longestStart:d.longestStart||START_DATE,longestEnd:d.longestEnd||BASE_DATE,updatedAt:now()};s.occurrences.push({id:`dc-plus:${Date.now()}-${Math.random()}`,trackerId:'daily-challenge',date,count:1,result:'complete',source:'manual',logType:'dc-authoritative',snippet:'Daily Challenge completed',createdAt:now()});write(s);location.reload()}
function resetStreak(){if(!confirm('Reset the active Daily Challenge streak to 0?'))return;const s=ensureShape(read()),d=streak(s);s.tideCounters.dailyChallenge={current:0,longest:d.longest,currentStart:null,lastCounted:today(),longestStart:d.longestStart||START_DATE,longestEnd:d.longestEnd||BASE_DATE,updatedAt:now()};write(s);location.reload()}
function setStreak(v){const s=ensureShape(read()),d=streak(s),n=Math.max(0,Number(v)||0);s.tideCounters.dailyChallenge={current:n,longest:Math.max(d.longest,n),currentStart:n?(d.start||shift(today(),-(n-1))):null,lastCounted:n?today():d.last,longestStart:d.longestStart||START_DATE,longestEnd:n>d.longest?today():(d.longestEnd||BASE_DATE),updatedAt:now()};write(s);location.reload()}
function setMonth(w,l){const s=ensureShape(read()),month=today().slice(0,7),old=s.monthlyReviews[month]||{};s.monthlyReviews[month]={...old,versusTotals:{...(old.versusTotals||{}),'monty-dc':{wins:Math.max(0,Number(w)||0),losses:Math.max(0,Number(l)||0),ties:0}},updatedAt:now()};write(s);location.reload()}
function setOverall(w,l){const s=ensureShape(read());s.tideCounters.montyOverall={wins:Math.max(0,Number(w)||0),losses:Math.max(0,Number(l)||0),updatedAt:now()};write(s);location.reload()}
function monty(result){const s=ensureShape(read()),month=today().slice(0,7),year=Number(month.slice(0,4)),m=monthRecord(s,month),a=overallRecord(s),y=cleanRecord(s.tideCounters.montyYears[year]);if(result==='win'){m.wins++;a.wins++;y.wins++}else{m.losses++;a.losses++;y.losses++}const old=s.monthlyReviews[month]||{};s.monthlyReviews[month]={...old,versusTotals:{...(old.versusTotals||{}),'monty-dc':{...m,ties:0}},updatedAt:now()};s.tideCounters.montyOverall={...a,updatedAt:now()};s.tideCounters.montyYears[year]={...y,updatedAt:now()};s.occurrences.push({id:`monty-final:${Date.now()}-${Math.random()}`,trackerId:'monty-dc',date:today(),count:1,result,source:'manual',logType:'monty-authoritative',snippet:`Daily Challenge vs Monty: ${result.toUpperCase()}`,createdAt:now()});write(s);location.reload()}

function selectedDay(){const t=root?.querySelector('.day-nav-center h1')?.textContent?.trim();if(!t)return null;const d=new Date(`${t.replace(/^[A-Za-z]+,\s*/,'')} 12:00:00`);return Number.isNaN(d.getTime())?null:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function overwriteBaseDisplays(s){const d=streak(s);root?.querySelectorAll('.stat-label').forEach(label=>{if(label.textContent.trim()==='DC Streak'){const box=label.parentElement?.querySelector('.big-stat');if(box)box.textContent=String(d.current);const sub=label.parentElement?.querySelector('.tiny');if(sub)sub.textContent=d.current>0?'ACTIVE':'INACTIVE'}});root?.querySelectorAll('.record-card').forEach(c=>{const l=c.querySelector('.stat-label')?.textContent?.trim();if(l==='Longest Daily Challenge'){const v=c.querySelector('.record-value'),detail=c.querySelector('.record-detail');if(v)v.textContent=`${d.longest} days`;if(detail)detail.textContent=`${short(d.longestStart||START_DATE)} → ${short(d.longestEnd||BASE_DATE)}`}})}
function injectToday(s){if(!root?.querySelector('#day-editor')||document.querySelector('#geo-final-one'))return;const date=selectedDay();if(!date)return;const d=streak(s),month=today().slice(0,7),m=monthRecord(s,month),a=overallRecord(s),isToday=date===today(),x=document.createElement('section');x.id='geo-final-one';x.className='card';x.innerHTML=`<div class="card-header"><div><h3>GeoGuessr Daily Challenge</h3><div class="small muted">This is the authoritative counter.</div></div><span class="chip accent">${d.current>0?'ACTIVE':'INACTIVE'}</span></div><div style="text-align:center;padding:8px 0 14px"><div class="stat-label">CURRENT STREAK</div><div class="big-stat" style="font-size:62px;line-height:1.05;margin-top:6px">${d.current}</div><div class="tiny subtle" style="margin-top:6px">${d.current?`Started ${short(d.start)}`:'No active streak'}</div></div>${isToday?`<button id="geo-plus" class="button primary" style="width:100%;font-size:18px;padding:14px">↑ +1 Daily Challenge</button>`:''}<div class="section-title">VS MONTY</div><div class="grid grid-2" style="margin-bottom:12px">${card('This Month',`${m.wins}-${m.losses}`)}${card('All Time',`${a.wins}-${a.losses}`)}</div>${isToday?`<div class="grid grid-2"><button id="geo-win" class="button primary">WIN · I Beat Monty</button><button id="geo-loss" class="button">LOSS · Monty Beat Me</button></div><div class="tiny subtle" style="margin-top:8px;text-align:center">No scores. No ties. A new month starts at 0-0.</div>`:''}`;(root.querySelector('.right-stack')||root).prepend(x);x.querySelector('#geo-plus')?.addEventListener('click',plusOne);x.querySelector('#geo-win')?.addEventListener('click',()=>monty('win'));x.querySelector('#geo-loss')?.addEventListener('click',()=>monty('loss'))}
function injectTrackers(s){if((root?.querySelector('.page-head h1')?.textContent||'')!=='Trackers'||document.querySelector('#geo-controls-one'))return;const d=streak(s),m=monthRecord(s),a=overallRecord(s),x=document.createElement('section');x.id='geo-controls-one';x.className='card';x.style.marginBottom='16px';x.innerHTML=`<div class="card-header"><div><h2>GeoGuessr Controls</h2><div class="small muted">These are the authoritative controls.</div></div><span class="chip accent">LIVE</span></div><div class="records-grid">${card('Current DC Streak',d.current,d.current?`Started ${short(d.start)}`:'Inactive')}${card('Longest DC Streak',`${d.longest} days`,`${short(d.longestStart||START_DATE)} → ${short(d.longestEnd||BASE_DATE)}`)}${card('Monty This Month',`${m.wins}-${m.losses}`)}${card('Monty All Time',`${a.wins}-${a.losses}`)}</div><div class="grid grid-3" style="margin-top:14px"><button id="gc-plus" class="button primary">↑ +1 Daily Challenge</button><button id="gc-win" class="button primary">WIN vs Monty</button><button id="gc-loss" class="button">LOSS vs Monty</button></div><div class="section-title">CORRECT DAILY CHALLENGE</div><div class="filter-row"><input id="gc-dc" class="input" type="number" min="0" value="${d.current}" style="max-width:180px"><button id="gc-dc-set" class="button">Set Current Streak</button><button id="gc-reset" class="button ghost">Streak Lost / Reset</button></div><div class="section-title">CORRECT THIS MONTH VS MONTY</div><div class="grid grid-2"><label class="label">Wins<input id="gc-mw" class="input" type="number" min="0" value="${m.wins}"></label><label class="label">Losses<input id="gc-ml" class="input" type="number" min="0" value="${m.losses}"></label></div><button id="gc-ms" class="button" style="margin-top:10px">Set This Month</button><div class="section-title">CORRECT ALL-TIME VS MONTY</div><div class="grid grid-2"><label class="label">Wins<input id="gc-aw" class="input" type="number" min="0" value="${a.wins}"></label><label class="label">Losses<input id="gc-al" class="input" type="number" min="0" value="${a.losses}"></label></div><button id="gc-as" class="button" style="margin-top:10px">Set All-Time</button>`;const first=root.querySelector(':scope > .card');if(first)first.before(x);else root.prepend(x);x.querySelector('#gc-plus').onclick=plusOne;x.querySelector('#gc-win').onclick=()=>monty('win');x.querySelector('#gc-loss').onclick=()=>monty('loss');x.querySelector('#gc-dc-set').onclick=()=>setStreak(x.querySelector('#gc-dc').value);x.querySelector('#gc-reset').onclick=resetStreak;x.querySelector('#gc-ms').onclick=()=>setMonth(x.querySelector('#gc-mw').value,x.querySelector('#gc-ml').value);x.querySelector('#gc-as').onclick=()=>setOverall(x.querySelector('#gc-aw').value,x.querySelector('#gc-al').value);root.querySelectorAll('.tracker-row').forEach(r=>{const n=r.querySelector('.tracker-name b')?.textContent?.trim();if(n==='Daily Challenge'||n==='Daily Challenge vs Monty')r.style.display='none'})}
function injectRecords(s){if((root?.querySelector('.page-head h1')?.textContent||'')!=='Personal Records'||document.querySelector('#geo-records-one'))return;const d=streak(s),m=monthRecord(s),a=overallRecord(s),grid=root.querySelector('.records-grid');if(!grid)return;const x=document.createElement('div');x.id='geo-records-one';x.style.display='contents';x.innerHTML=`${card('Current Daily Challenge',`${d.current} days`,d.current?`ACTIVE · Started ${short(d.start)}`:'INACTIVE')}${card('Monty This Month',`${m.wins}-${m.losses}`)}${card('Monty All Time',`${a.wins}-${a.losses}`)}`;grid.prepend(x)}
function injectMonthly(s){if(!root?.querySelector('#month-select')||document.querySelector('#geo-month-one'))return;const month=root.querySelector('#month-select').value,r=monthRecord(s,month),x=document.createElement('section');x.id='geo-month-one';x.className='card';x.style.marginTop='16px';x.innerHTML=`<div class="card-header"><div><h2>Daily Challenge vs Monty</h2><div class="small muted">Win-loss only.</div></div><span class="chip accent">${r.wins}-${r.losses}</span></div><div class="grid grid-2">${card('Wins',r.wins)}${card('Losses',r.losses)}</div>`;root.append(x)}
function answerAsk(){const input=root?.querySelector('#ask-input'),out=root?.querySelector('#ask-results');if(!input||!out)return;const q=input.value.toLowerCase(),s=ensureShape(read()),d=streak(s),m=monthRecord(s),a=overallRecord(s),y=cleanRecord(s.tideCounters.montyYears?.[Number(today().slice(0,4))]);let primary=null,detail='';if(/daily challenge/.test(q)&&/streak/.test(q)&&!/monty/.test(q)){primary=String(d.current);detail=`Current GeoGuessr Daily Challenge streak${d.start?` · started ${short(d.start)}`:''}.`}else if(/monty/.test(q)&&/(record|wins?|loss|versus|\bvs\b)/.test(q)){const r=/this month/.test(q)?m:/this year/.test(q)?y:a;primary=`${r.wins}-${r.losses}`;detail=`Daily Challenge record versus Monty ${/this month/.test(q)?'this month':/this year/.test(q)?'this year':'all time'}.`}if(primary!==null)out.innerHTML=`<div class="answer-card"><div class="eyebrow">ANSWER</div><div class="answer-primary">${esc(primary)}</div><div class="answer-explain">${esc(detail)}</div></div>`}
document.addEventListener('click',e=>{if(e.target?.closest?.('#ask-go'))setTimeout(answerAsk,0)});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='ask-input')setTimeout(answerAsk,0)});

const initial=ensureShape(read());const didRepair=repair(initial);
if(didRepair&&!sessionStorage.getItem('tide_geo_final_reloaded')){sessionStorage.setItem('tide_geo_final_reloaded','1');location.reload()}
else{let pending=false;const run=()=>{pending=false;const s=ensureShape(read());overwriteBaseDisplays(s);injectToday(s);injectTrackers(s);injectRecords(s);injectMonthly(s)};new MutationObserver(()=>{if(pending)return;pending=true;queueMicrotask(run)}).observe(root,{childList:true,subtree:true});run();}
