import {BASELINE_DATE,activityRange,aggregateAllTime,allTimeTotal,clean,esc,hours,knownLastPlayed,platformLabel,shortDate} from './gaming-data.js';
const root=document.querySelector('#view-root');
function period(q){const l=q.toLowerCase(),cy=new Date().getFullYear();if(/all[ -]?time|ever|lifetime/.test(l))return{all:true};const months=['january','february','march','april','may','june','july','august','september','october','november','december'],mi=months.findIndex(m=>l.includes(m)),ym=l.match(/\b(20\d{2})\b/)?.[1];if(mi>=0){const y=Number(ym||cy),m=String(mi+1).padStart(2,'0'),d=new Date(y,mi+1,0).getDate();return{all:false,start:`${y}-${m}-01`,end:`${y}-${m}-${String(d).padStart(2,'0')}`,label:`${months[mi]} ${y}`};}if(/this month/.test(l)){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),last=new Date(y,d.getMonth()+1,0).getDate();return{all:false,start:`${y}-${m}-01`,end:`${y}-${m}-${String(last).padStart(2,'0')}`,label:'this month'};}if(ym||/this year/.test(l)){const y=Number(ym||cy);return{all:false,start:`${y}-01-01`,end:`${y}-12-31`,label:String(y)};}return{all:true};}
function platform(q){const l=q.toLowerCase();if(/ps5/.test(l))return'ps5';if(/ps4/.test(l))return'ps4';if(/xbox/.test(l))return'xbox';if(/nintendo|switch/.test(l))return'nintendo';if(/steam/.test(l))return'steam';if(/ubisoft/.test(l))return'ubisoft';if(/playstation/.test(l))return'playstation';if(/console/.test(l))return'console';if(/\bpc\b/.test(l))return'pc';return'all';}
function answer(q){const l=q.toLowerCase();if(!/(game|gaming|playtime|played|steam|ps5|ps4|xbox|nintendo|switch|ubisoft|console)/.test(l))return null;const pf=platform(q),p=period(q),all=aggregateAllTime(pf),game=all.slice().sort((a,b)=>b.title.length-a.title.length).find(g=>l.includes(g.title.toLowerCase())||l.includes(clean(g.title))),d=p.all?{games:all,total:allTimeTotal(pf),coverageStart:BASELINE_DATE}:activityRange(p.start,p.end,pf),rank=[...d.games].sort((a,b)=>b.minutes-a.minutes),n=Math.min(25,Math.max(1,Number(l.match(/top\s+(\d+)/)?.[1]||(/most played/.test(l)?1:5))));
if(game&&/(last play|last time|when did)/.test(l))return{primary:shortDate(game.lastPlayed),detail:`True last-played date for ${game.title}, using the newest date across every tracked source.`,items:game.sources.map(s=>`${platformLabel(s.platform)} · ${hours(s.minutes)} · last ${shortDate(s.lastPlayed)}`)};
if(game&&/(platform|breakdown|where.*play|how much.*on)/.test(l))return{primary:hours(game.minutes),detail:`${game.title} lifetime platform breakdown.`,items:Object.entries(game.platformMinutes).sort((a,b)=>b[1]-a[1]).map(([x,m])=>`${platformLabel(x)} · ${hours(m)}`)};
if(game){if(p.all)return{primary:hours(game.minutes),detail:`${game.title} across all tracked platforms.`,items:Object.entries(game.platformMinutes).sort((a,b)=>b[1]-a[1]).map(([x,m])=>`${platformLabel(x)} · ${hours(m)}`)};if(!d.coverageStart||p.end<d.coverageStart)return{primary:'Historical hours unavailable',detail:`T.I.D.E. knows ${game.title}'s lifetime total (${hours(game.minutes)}) and last-played history, but does not invent old month/year hour splits before ${shortDate(BASELINE_DATE)}.`};const row=d.games.find(x=>x.key===game.key);return{primary:hours(row?.minutes||0),detail:`Tracked ${game.title} playtime for ${p.label}${p.start<d.coverageStart?` since ${shortDate(d.coverageStart)}`:''}.`};}
if(/total.*hour|how many.*hour|gaming hours|playtime total/.test(l))return{primary:hours(d.total),detail:p.all?'Lifetime gaming hours across the selected platform filter.':d.coverageStart&&p.end>=d.coverageStart?`Tracked gaming hours for ${p.label}${p.start<d.coverageStart?` since ${shortDate(d.coverageStart)}`:''}.`:`Exact historical period hours were not captured before ${shortDate(BASELINE_DATE)}.`};
if(/last played|recent/.test(l)&&p.all){const recent=[...all].sort((a,b)=>String(b.lastPlayed).localeCompare(String(a.lastPlayed)));return{primary:recent[0]?.title||'—',detail:recent[0]?`Last played ${shortDate(recent[0].lastPlayed)}.`:'No gaming history.',items:recent.slice(0,n).map(g=>`${g.title} · ${shortDate(g.lastPlayed)}`)};}
if(!p.all&&(!d.coverageStart||p.end<d.coverageStart)){const known=knownLastPlayed(p.start,p.end,pf);return{primary:'Historical period is reconstructed',detail:`Exact playtime was not captured before ${shortDate(BASELINE_DATE)}. These games have known last-played dates in ${p.label}.`,items:known.slice(0,n).map(g=>`${g.title} · ${shortDate(g.lastPlayed)}`)};}
return{primary:rank[0]?.title||'—',detail:rank[0]?`${hours(rank[0].minutes)} · ${p.all?'all time':p.label}`:'No tracked gaming activity.',items:rank.slice(0,n).map((g,i)=>`${i+1}. ${g.title} · ${hours(g.minutes)}`)};}
function render(a){return`<div class="answer-card"><div class="eyebrow">GAMING ANSWER</div><div class="answer-primary">${esc(a?.primary||'—')}</div>${a?.detail?`<div class="answer-explain">${esc(a.detail)}</div>`:''}${a?.items?.length?`<div class="history-list" style="margin-top:16px">${a.items.map(x=>`<div class="result-row">${esc(x)}</div>`).join('')}</div>`:''}</div>`;}
function decorate(){if((root?.querySelector('.page-head h1')?.textContent||'')!=='Ask T.I.D.E.')return;const s=root.querySelector('.ask-suggestions');if(s&&!s.querySelector('[data-gaming-q]'))for(const [label,q] of [['Most played game','What is my most played game all time?'],['GTA V hours','How many hours have I played Grand Theft Auto V?'],['PC top 5','What are my top 5 PC games all time?']]){const b=document.createElement('button');b.className='chip';b.dataset.gamingQ=q;b.textContent=label;b.onclick=()=>{root.querySelector('#ask-input').value=q;root.querySelector('#ask-results').innerHTML=render(answer(q));};s.append(b);}}
function run(){const input=root.querySelector('#ask-input'),a=answer(input?.value||'');if(a)root.querySelector('#ask-results').innerHTML=render(a);}
export function wireGamingAsk(){document.addEventListener('click',e=>{if(e.target.closest('[data-view="ask"]'))setTimeout(decorate,0);if(e.target.closest('#ask-go'))setTimeout(run,0);});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('#ask-input'))setTimeout(run,0);});setTimeout(decorate,0);}
