import { isAuthenticated, json } from '../../_lib/auth.js';

const EXOPHASE_USER='danteivery';
const STEAM_ID='76561199195640502';
const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36';
function dateFromUnix(value){const n=Number(value)||0;return n>0?new Date(n*1000).toISOString().slice(0,10):'';}
function playMinutes(game){const u=game?.playtimeUnits;if(u&&(u.hours!=null||u.minutes!=null))return Math.max(0,Math.round((Number(u.hours)||0)*60)+(Number(u.minutes)||0));const s=String(game?.playtime||''),h=Number(s.match(/([\d.]+)\s*h/i)?.[1]||0),m=Number(s.match(/(\d+)\s*m/i)?.[1]||0);return Math.max(0,Math.round(h*60)+m);}
function platformFor(game){const env=String(game?.meta?.environment_slug||'').toLowerCase(),slugs=(game?.meta?.platforms||[]).map(p=>String(p?.slug||p?.name||'').toLowerCase()),has=x=>slugs.some(s=>s.includes(x));if(env==='steam'||has('steam'))return'steam';if(env==='nintendo'||has('switch'))return'nintendo';if(env==='uplay'||env==='ubisoft')return'ubisoft';if(env==='origin'||env==='ea')return'ea';if(env==='gog')return'gog';if(env==='epic')return'epic';if(env==='xbox'||has('xbox'))return'xbox';if(env==='psn'||has('playstation')||has('ps4')||has('ps5')){const p4=has('ps4'),p5=has('ps5');if(p5&&!p4)return'ps5';if(p4&&!p5)return'ps4';return'playstation';}if(env==='windows'||has('windows'))return'windows';return env||'other';}
async function resolveExophaseId(env){if(env?.EXOPHASE_PLAYER_ID)return String(env.EXOPHASE_PLAYER_ID);const r=await fetch(`https://www.exophase.com/user/${EXOPHASE_USER}/`,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'}}),text=await r.text();if(!r.ok)throw new Error(`profile lookup returned ${r.status}`);const m=text.match(/playerProfileId\s*[=:]\s*['\"]?([0-9]+)/i)||text.match(/\"playerProfileId\"\s*:\s*\"?([0-9]+)/i);if(!m)throw new Error('player id was not exposed by the profile page');return m[1];}
async function exophase(env){try{const playerId=await resolveExophaseId(env),games=[];for(let page=1;page<=200;page++){const u=`https://api.exophase.com/public/player/${encodeURIComponent(playerId)}/games?page=${page}&environment=&sort=1&showHidden=0&me=0&query=`,r=await fetch(u,{headers:{'user-agent':UA,'accept':'application/json, text/plain, */*','referer':'https://www.exophase.com/'}});if(!r.ok)throw new Error(`games feed returned ${r.status}`);const body=await r.json();if(!body?.success){if(page===1)throw new Error('games feed returned success=false');break;}const rows=Array.isArray(body.games)?body.games:[];if(!rows.length)break;for(const g of rows){const title=String(g?.meta?.title||'').trim();if(!title)continue;const environment=String(g?.meta?.environment_slug||'').toLowerCase(),masterId=g.master_id||g.meta?.master_id||null,masterPlayerId=g.master_playerid||null;games.push({sourceKey:`exophase:${environment||'unknown'}:${masterPlayerId||'player'}:${masterId||games.length}`,title,minutes:playMinutes(g),lastPlayed:dateFromUnix(g.lastplayed_utc||g.lastplayed),platform:platformFor(g),environment,image:g.resource_standard||g.resource_tile||g.meta?.image||'',masterId,masterPlayerId});}if(rows.length<50)break;}return{ok:true,playerId,games};}catch(error){return{ok:false,error:String(error?.message||error),games:[]};}}
function decodeXml(s){return String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'\"').replace(/&#39;/g,"'");}
function tag(block,name){const m=block.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,'i'));return decodeXml(m?.[1]||'').trim();}
function titleKey(value){return String(value||'').replace(/[™®©]/g,'').replace(/[^a-z0-9]+/gi,' ').trim().toLowerCase();}
function addSteam(map,row,source='steam-page'){
  const appId=Number(row?.appid??row?.appID??row?.appId)||0,title=String(row?.name||row?.title||'').trim(),minutes=Math.max(0,Math.round(Number(row?.playtime_forever??row?.minutes??0)||0));
  if(!appId&&!title)return;
  const key=appId?`app:${appId}`:`title:${titleKey(title)}`;
  const existing=map.get(key);
  const iconHash=String(row?.img_icon_url||'').trim(),image=String(row?.image||row?.logo||'').trim()||(appId&&iconHash?`https://media.steampowered.com/steamcommunity/public/images/apps/${appId}/${iconHash}.jpg`:''),lastPlayed=row?.lastPlayed||dateFromUnix(row?.rtime_last_played);
  const next={sourceKey:appId?`steam:${appId}`:`steam:title:${titleKey(title)}`,appId:appId||null,title:title||existing?.title||`Steam ${appId}`,minutes,lastPlayed,platform:'steam',environment:'steam',image,hoursLast2Weeks:Number(row?.playtime_2weeks||0)/60,source};
  if(!existing||next.minutes>existing.minutes)map.set(key,{...existing,...next,lastPlayed:existing?.lastPlayed>next.lastPlayed?existing.lastPlayed:next.lastPlayed,image:next.image||existing?.image||''});
  else if(lastPlayed&&lastPlayed>String(existing.lastPlayed||'')){existing.lastPlayed=lastPlayed;map.set(key,existing);}
}
function parseJsonStringLiteral(text,marker){const start=text.indexOf(marker);if(start<0)return null;const tail=text.slice(start+marker.length),m=tail.match(/^\s*\(\s*("(?:\\.|[^"\\])*")\s*\)/);if(!m)return null;try{return JSON.parse(m[1]);}catch{return null;}}
function balancedJson(text,marker){const start=text.indexOf(marker);if(start<0)return null;let i=start+marker.length;while(i<text.length&&text[i]!=='['&&text[i]!=='{')i++;if(i>=text.length)return null;const open=text[i],close=open==='['?']':'}';let depth=0,quote='',escape=false;for(let j=i;j<text.length;j++){const c=text[j];if(quote){if(escape)escape=false;else if(c==='\\')escape=true;else if(c===quote)quote='';continue;}if(c==='"'||c==="'"){quote=c;continue;}if(c===open)depth++;else if(c===close){depth--;if(depth===0)return text.slice(i,j+1);}}return null;}
function collectSteam(value,map,depth=0){if(value==null||depth>12)return;if(Array.isArray(value)){for(const x of value)collectSteam(x,map,depth+1);return;}if(typeof value==='object'){if((value.appid!=null||value.appID!=null||value.appId!=null)&&(value.playtime_forever!=null||value.minutes!=null))addSteam(map,value);for(const v of Object.values(value))collectSteam(v,map,depth+1);return;}if(typeof value==='string'&&value.length<8000000){const t=value.trim();if((t.startsWith('{')||t.startsWith('['))&&(t.includes('OwnedGames')||t.includes('rgGames')||t.includes('playtime_forever'))){try{collectSteam(JSON.parse(t),map,depth+1);}catch{}}}}
function parseSteamHtml(html,map){
  const renderText=parseJsonStringLiteral(html,'window.SSR.renderContext=JSON.parse');
  if(renderText)try{collectSteam(JSON.parse(renderText),map);}catch{}
  for(const marker of ['window.SSR.loaderData =','window.SSR.loaderData=','var rgGames =','var rgGames=']){const raw=balancedJson(html,marker);if(raw)try{collectSteam(JSON.parse(raw),map);}catch{}}
  const direct=html.match(/var\s+rgGames\s*=\s*(\[[\s\S]*?\])\s*;/);if(direct)try{collectSteam(JSON.parse(direct[1]),map);}catch{}
}
function parseSteamXml(xml,map){for(const m of xml.matchAll(/<game>([\s\S]*?)<\/game>/gi)){const block=m[1],appId=tag(block,'appID'),title=tag(block,'name'),raw=tag(block,'hoursOnRecord').replace(/,/g,''),hrs=Number(raw||0);if(!title||!appId)continue;addSteam(map,{appid:Number(appId),name:title,playtime_forever:Math.max(0,Math.round(hrs*60)),playtime_2weeks:Math.max(0,Math.round(Number(tag(block,'hoursLast2Weeks').replace(/,/g,'')||0)*60)),logo:tag(block,'logo')},'steam-xml-fallback');}}
async function steam(){try{const headers={'user-agent':UA,'accept':'text/html,application/xhtml+xml,application/xml;q=0.8','accept-language':'en-US,en;q=0.9'},map=new Map();const [page,xml]=await Promise.allSettled([fetch(`https://steamcommunity.com/profiles/${STEAM_ID}/games/?tab=all`,{headers}),fetch(`https://steamcommunity.com/profiles/${STEAM_ID}/games?xml=1`,{headers})]);if(page.status==='fulfilled'&&page.value.ok)parseSteamHtml(await page.value.text(),map);if(xml.status==='fulfilled'&&xml.value.ok)parseSteamXml(await xml.value.text(),map);const games=[...map.values()];if(!games.length)throw new Error('Steam public games page returned no owned-game playtime');return{ok:true,steamId:STEAM_ID,games,method:'community-page-ssr+xml-fallback'};}catch(error){return{ok:false,error:String(error?.message||error),games:[]};}}
function mergeExophaseSteam(stm,exo){if(!exo?.ok)return stm;const exoSteam=(exo.games||[]).filter(x=>x.environment==='steam'),byTitle=new Map((stm.games||[]).map((x,i)=>[titleKey(x.title),i]));for(const x of exoSteam){const key=titleKey(x.title);if(!key)continue;const i=byTitle.get(key);if(i!=null){const cur=stm.games[i];if((Number(cur.minutes)||0)<=0&&(Number(x.minutes)||0)>0)cur.minutes=Number(x.minutes)||0;if(x.lastPlayed>String(cur.lastPlayed||''))cur.lastPlayed=x.lastPlayed;if(!cur.image&&x.image)cur.image=x.image;continue;}if((Number(x.minutes)||0)<=0)continue;byTitle.set(key,stm.games.length);stm.games.push({sourceKey:`steam:exophase:${x.masterPlayerId||'player'}:${x.masterId||key}`,appId:null,title:x.title,minutes:Number(x.minutes)||0,lastPlayed:x.lastPlayed||'',platform:'steam',environment:'steam',image:x.image||'',hoursLast2Weeks:0,source:'exophase-steam-fallback'});}if(!stm.ok&&stm.games.length){stm.ok=true;stm.error='';stm.method='exophase-steam-fallback';}return stm;}
export async function onRequestGet({env,request}){if(!(await isAuthenticated(env,request)))return json({error:'Connect T.I.D.E. Cloud Sync first.'},401);const [exo,rawSteam]=await Promise.all([exophase(env),steam()]),stm=mergeExophaseSteam(rawSteam,exo);return json({capturedAt:new Date().toISOString(),exophase:exo,steam:stm,ruleNotes:{legacyPs4:'19 visible games plus 118 unassigned lifetime hours',ubisoft:'One stable Exophase Ubisoft player identity is selected from Motorfest and all games on that PC identity are counted; duplicate Ubisoft identities are ignored.',steam:'Current Steam community games-page SSR data is primary; deprecated XML and Exophase Steam data are fallbacks.'}});}
