import { isAuthenticated, json } from '../../_lib/auth.js';

const EXOPHASE_USER='danteivery';
const STEAM_ID='76561199195640502';
const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36';
function dateFromUnix(value){const n=Number(value)||0;return n>0?new Date(n*1000).toISOString().slice(0,10):'';}
function playMinutes(game){const u=game?.playtimeUnits;if(u&&(u.hours!=null||u.minutes!=null))return Math.max(0,(Number(u.hours)||0)*60+(Number(u.minutes)||0));const s=String(game?.playtime||''),h=Number(s.match(/(\d+)\s*h/i)?.[1]||0),m=Number(s.match(/(\d+)\s*m/i)?.[1]||0);return h*60+m;}
function platformFor(game){const env=String(game?.meta?.environment_slug||'').toLowerCase(),slugs=(game?.meta?.platforms||[]).map(p=>String(p?.slug||p?.name||'').toLowerCase()),has=x=>slugs.some(s=>s.includes(x));if(env==='steam'||has('steam'))return'steam';if(env==='nintendo'||has('switch'))return'nintendo';if(env==='uplay'||env==='ubisoft')return'ubisoft';if(env==='origin'||env==='ea')return'ea';if(env==='gog')return'gog';if(env==='epic')return'epic';if(env==='xbox'||has('xbox'))return'xbox';if(env==='psn'||has('playstation')||has('ps4')||has('ps5')){const p4=has('ps4'),p5=has('ps5');if(p5&&!p4)return'ps5';if(p4&&!p5)return'ps4';return'playstation';}if(env==='windows'||has('windows'))return'windows';return env||'other';}
async function resolveExophaseId(env){if(env?.EXOPHASE_PLAYER_ID)return String(env.EXOPHASE_PLAYER_ID);const r=await fetch(`https://www.exophase.com/user/${EXOPHASE_USER}/`,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'}}),text=await r.text();if(!r.ok)throw new Error(`profile lookup returned ${r.status}`);const m=text.match(/playerProfileId\s*[=:]\s*['\"]?([0-9]+)/i)||text.match(/\"playerProfileId\"\s*:\s*\"?([0-9]+)/i);if(!m)throw new Error('player id was not exposed by the profile page');return m[1];}
async function exophase(env){try{const playerId=await resolveExophaseId(env),games=[];for(let page=1;page<=100;page++){const u=`https://api.exophase.com/public/player/${encodeURIComponent(playerId)}/games?page=${page}&environment=&sort=1&showHidden=0`,r=await fetch(u,{headers:{'user-agent':UA,'accept':'application/json, text/plain, */*','referer':'https://www.exophase.com/'}});if(!r.ok)throw new Error(`games feed returned ${r.status}`);const body=await r.json();if(!body?.success||!Array.isArray(body.games)||!body.games.length)break;for(const g of body.games){const title=String(g?.meta?.title||'').trim();if(!title)continue;const environment=String(g?.meta?.environment_slug||'').toLowerCase();games.push({sourceKey:`exophase:${environment||'unknown'}:${g.master_id||g.meta?.master_id||games.length}`,title,minutes:playMinutes(g),lastPlayed:dateFromUnix(g.lastplayed_utc||g.lastplayed),platform:platformFor(g),environment,image:g.resource_standard||g.resource_tile||g.meta?.image||'',masterId:g.master_id||g.meta?.master_id||null});}}return{ok:true,playerId,games};}catch(error){return{ok:false,error:String(error?.message||error),games:[]};}}
function decodeXml(s){return String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'\"').replace(/&#39;/g,"'");}
function tag(block,name){const m=block.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,'i'));return decodeXml(m?.[1]||'').trim();}
async function steam(){try{const r=await fetch(`https://steamcommunity.com/profiles/${STEAM_ID}/games?xml=1`,{headers:{'user-agent':UA,'accept':'application/xml,text/xml,text/html;q=0.9'}}),text=await r.text();if(!r.ok)throw new Error(`Steam library returned ${r.status}`);if(/<privacyMessage>/i.test(text))throw new Error('Steam game details are private');const games=[];for(const m of text.matchAll(/<game>([\s\S]*?)<\/game>/gi)){const block=m[1],appId=tag(block,'appID'),title=tag(block,'name'),hrs=Number(tag(block,'hoursOnRecord').replace(',','.')||0);if(!title||!appId)continue;games.push({sourceKey:`steam:${appId}`,appId:Number(appId),title,minutes:Math.max(0,Math.round(hrs*60)),hoursLast2Weeks:Number(tag(block,'hoursLast2Weeks').replace(',','.')||0),lastPlayed:'',platform:'steam',environment:'steam',image:tag(block,'logo')});}if(!games.length)throw new Error('Steam returned no public games');return{ok:true,steamId:STEAM_ID,games};}catch(error){return{ok:false,error:String(error?.message||error),games:[]};}}
export async function onRequestGet({env,request}){if(!(await isAuthenticated(env,request)))return json({error:'Connect T.I.D.E. Cloud Sync first.'},401);const [exo,stm]=await Promise.all([exophase(env),steam()]);return json({capturedAt:new Date().toISOString(),exophase:exo,steam:stm,ruleNotes:{legacyPs4:'19 visible games plus 118 unassigned lifetime hours',ubisoft:'Only the selected PC The Crew Motorfest Ubisoft source is counted',steam:'Steam XML is authoritative for Steam playtime; Exophase supplements last-played dates.'}});}
